### ISSUE TITLE
Provide a method for reading longer descriptions.

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#156]
The current description field only displays a small amount of text at once. This enhancement would be to make the description a long text box or a popup box.

**Comment by ewlarson** [comment]
Will need to convert our repeatable description field into a block like:

```ruby
    <%= f.repeatable_attr_input(:admin_note, build: :at_least_one) do |input_name, value| %>
      <div class="form-group">
        <%= f.input_field :admin_note, name: input_name, value: value, as: :text, class: "form-control", rows: 4 %>
      </div>
    <% end %>

```

**Comment by ewlarson** [comment]
As repeatable textarea elements, it'll look like this:

<img width="1405" alt="Screen Shot 2022-11-16 at 8 35 02 AM" src="https://user-images.githubusercontent.com/69827/202210229-65d0b0ed-0d21-41e6-b71f-2cb216ee47cb.png">
