### ISSUE TITLE
Incorporate multiple or complex geometries

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#203]
https://opengeometadata.org/docs/ogm-aardvark/geometry

**Comment by karenmajewicz** [comment]
to do: create a fixture

**Comment by ewlarson** [comment]
Need to support:

* Simple bounding box: "ENVELOPE(-111.1, -104.0, 45.0, 40.9)"
* Bermuda Triangle: "POLYGON((-80 25, -65 18, -64 33, -80 25))"
* Split bounding box for Alaska: "MULTIPOLYGON (((-179.3 51.1, -129.9 51.1, -129.9 71.5, -179.3 71.5, -179.3 51.1)),((172.3 51.2, 179.9 51.2, 179.9 53.1, 172.3 53.1, 172.3 51.2)))"

We can use RGeo's wkt_parser to validate POLYGON and MULTIPOLYGON:

```ruby 
poly = "POLYGON((-80 25, -65 18, -64 33, -80 25))"
parsed = RGeo::Cartesian::Factory.new().parse_wkt(poly)
=> #<RGeo::Cartesian::PolygonImpl:0x64c8 "POLYGON ((-80.0 25.0, -65.0 18.0, -64.0 33.0, -80.0 25.0))">
```

But! RGeo does not recognize the ENVELOPE syntax:

```ruby
bbox = "ENVELOPE(-18.6,52.3,37.17,-35.3)"
parsed = RGeo::Cartesian::Factory.new().parse_wkt(bbox)
=> Unknown type tag: "envelope". (RGeo::Error::ParseError)
```

**Comment by karenmajewicz** [comment]
Here is a fixture that we could use: https://github.com/OpenGeoMetadata/geobtaa/blob/main/aardvark/797ddf9a-41ae-4525-90e4-4238ea09079b.json

Not sure if the multipolygon syntax is correct yet; still testing
