### ISSUE TITLE
Add Date Created to main dashboard

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#207]
It would be useful to be able to select recently added items from the dashboard.

The Date Created metadata includes a time stamp. Could we lop that off and just have them selectable by day (or maybe month)?

**Comment by ewlarson** [comment]
We could do a date range bucket using our `date_created_drsim` field. Would look something like this:

![Image](https://user-images.githubusercontent.com/69827/166501291-60b70127-8bc5-40ba-a24b-28047047cd7a.png)

Would that be helpful? If yes, what buckets would be best:

* Today 
* Yesterday
* This week
* Last week
* This month
* Last month
* This quarter
* Last quarter
* This year
* Last year

Let me know!

**Comment by karenmajewicz** [comment]
These are the ones that I would mostly use:
- Today
- This week
- This month
- Last month
- This quarter
- This year
----
But, I can also envision those predefined & changing buckets not always working. Would there be a way of specifying a time period? Like "January 2022"?

**Comment by ewlarson** [comment]
We could have these defined time period buckets and an additional date picker filter (you choose start and end dates for the range).

**Comment by karenmajewicz** [comment]
That would be ideal if it is not too hard to implement.
