### ISSUE TITLE
Add Date Created to Item Edit page

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#216]
When viewing an item, the Date Created should display somewhere. 

Related issue: #207

**Comment by ewlarson** [comment]
Added the `:created_at` and `updated_at` fields to the Life Cycle block of the item#edit view, as disabled inputs -- these values are automatically set by Rails when a row is created and when a row is updated in the database. 

<img width="1410" alt="Screen Shot 2022-06-06 at 1 36 11 PM" src="https://user-images.githubusercontent.com/69827/172224789-b81e3a8f-6069-4861-b711-82e73afdeb0b.png">
