### ISSUE TITLE
Determine a method for tracking and prompting re-accessions from external sources

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#217]
We currently organize all of the sources in the Geoportal as "[Websites](https://geo.btaa.org/?f%5Bgbl_resourceClass_sm%5D%5B%5D=Websites&q=&search_field=all_fields)." Here is a lifecycle for Websites:

1. Someone identifies a new source - it may be a website of datasets, a digital library, and interactive application, etc.
2. This source is added to the geoportal as a Resource Class "website".
3. If applicable, the actual items in the website are harvested into the geoportal. This might happen right away or the task might get queued to happen at a later date. Items are linked to the website using the "Is Part Of" relationship.
4. At various intervals, we "re-accession" the website's content to stay up to date with changes, deletions, and additions.
----
I am interested in finding a way for GEOMG to assist with tracking list item 4. When I was using Airtable, I had a setup where I had a calculated field showing the last time items from a website had been harvested. I could sort by date and tend to the websites that had not been looked at in awhile.

Maybe there is a way of doing this with Blazer?

**Comment by ewlarson** [comment]
We have the "updated_at" data in Solr, so we can always sort by that in GEOMG. Rather lo-fi solution, but perhaps good enough for now? Unless you're envisioning an internal "todo list" of some kind.

Added "Updated At" as sorting options to [geomgdev](https://geomgdev.lib.umn.edu/documents?f%5Bgbl_resourceClass_sm%5D%5B%5D=Websites&rows=20&sort=date_modified_dtsi+asc):

![Image](https://user-images.githubusercontent.com/69827/172386606-5dc97638-968b-4d5c-9b45-39744543c77c.png)

**Comment by karenmajewicz** [comment]
I have a solution for this that will work sufficiently - This [query in Blazer](https://geomg.lib.umn.edu/blazer/queries/37-last-updated-by-code) will show the most recent Date Created per code. I can scan to the bottom to see Codes that I haven't re-accessioned in a while.
