### ISSUE TITLE
Create method for batch export and deletion of multiple downloads

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#221]

**Comment by ewlarson** [comment]
Temporary work around is to delete the Document, which will delete all associated DocumentDownload objects.

**Comment by ewlarson** [comment]
![Image](https://user-images.githubusercontent.com/69827/202307062-18e638d1-7b35-4eca-9908-ea9c20fb54ec.png)


![Image](https://user-images.githubusercontent.com/69827/202306966-b79d0bab-1da2-4ca1-aee2-e7f385517121.png)

**Comment by karenmajewicz** [comment]
I tested deleting and adding download links - this works very well. The example CSV File documentation is helpful as well.
