### ISSUE TITLE
Cannot update Status field with batch imports

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#225]
The [b1g_status_s](https://geobtaa.github.io/metadata/b1g-custom-elements/#status) field does not change when I upload updated CSVs.

It used to have controlled values, but we removed those in #181. However, it still seems to default to 'Active' when I upload new records and will not change if I upload different values. We must still have some code that is tying this field to the controlled values like here: https://github.com/geobtaa/geomg/blob/16764fc6cf9fd9d22d13126932784613814ec951/app/models/import_btaa.rb#L45-L48

Can we make this field Optional and remove any defaults?

**Comment by ewlarson** [comment]
Fix is up on https://geomgdev.lib.umn.edu/ for review.
