### ISSUE TITLE
Minor interface cleanup

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#226]
Before offering this as a public app, we should clean up a few minor interface issues. This ticket can serve as a log as those come up:

- [x] - The typo "successfull" appears in a few places (https://github.com/geobtaa/geomg/search?q=successfull)
- [x] - On the Bulk Action page, a list of Identifiers for selected items will appear. These still link to local host (i.e. http://localhost:3001/catalog/1f3cf343-bad9-427b-8416-6552954aa301)
- [x] Remove all footer links except one for "OpenGeoMetadata" (https://opengeometadata.org)

**Comment by ewlarson** [comment]
Adding buttons to view the Bulk Action item in GEOMG or the Geoportal:

<img width="1724" alt="Screen Shot 2022-09-16 at 11 39 37 AM" src="https://user-images.githubusercontent.com/69827/190688045-e67acb61-8553-49e9-bf7c-2b379bbfaeda.png">
