### ISSUE TITLE
Dev site not processing any CSV imports

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#233]
The last several imports (https://geomgdev.lib.umn.edu/imports) have not worked:

- There is a record of uploading the CSV, but no records are listed as Success or Failed.
- The last successful import was 2022-09-29.
- The same CSV files import fine into the prod site
- Exports work fine. (Exports were broken last week, but fixed by restarting Puma; see #232 )

**Comment by ewlarson** [comment]
Sounds like background job processing is down again? @mberkowski

**Comment by mberkowski** [comment]
Hmmmm. We just patched the dev host. I will look.

**Comment by mberkowski** [comment]
System patches earlier meant that Gems had to be rebuilt on redeploy. Nothing put any errors into logs to this effect.
