### ISSUE TITLE
Review purpose of "Bulk Actions" menu option

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#239]
Under the Admin Tools, there is an option for Bulk Actions. It presents a screen with a number of options for making changes, but I don't think it works. ?

Should we do some development on this or remove it from the menu?

<img width="216" alt="Screenshot 2022-11-16 at 5 44 54 PM" src="https://user-images.githubusercontent.com/2367677/202320706-684945a2-1ab9-4aaf-9291-2cdb5fd52277.png">

**Comment by ewlarson** [comment]
It _should_ work... but maybe something has gone arwy? I'll look into it.

**Comment by ewlarson** [comment]
So! Bulk actions does indeed work. It is the feature that lets you bulk change publication state from search results.

<img width="1722" alt="Screen Shot 2022-11-17 at 9 49 31 AM" src="https://user-images.githubusercontent.com/69827/202493159-fb483ae4-cea2-44fe-a9d0-6172b350c557.png">

However, the part that was never completed was using bulk actions to arbitrarily change field values, ex. Subject: "Foo" => Subject: "Bar".

I'll remove the button that shows the BulkActions#new view, which as it currently stands, would be next to impossible to use unless... well, you were me.

<img width="1722" alt="Screen Shot 2022-11-17 at 9 54 08 AM" src="https://user-images.githubusercontent.com/69827/202494678-f0153bf5-025b-4ffe-a81c-d8a5846ab10b.png">

Does that clear up this question?

**Comment by karenmajewicz** [comment]
Yes, it is that non-working form field I was thinking about. I am good with just removing the link to the "New Bulk Action" page.

**Comment by ewlarson** [comment]
Link to the New Bulk Action page is gone.
