### ISSUE TITLE
Fields on CSV export are unordered

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#265]
The last 2 exports have this order of fields:

WxS Identifier
Index Year
Date Range
Spatial Coverage
Bounding Box
Title
Alternative Title
B1G Language
Subject
Geometry
Creator
Creator ID
Publisher
Provider
Resource Class
Resource Type
Theme
Keyword
Temporal Coverage
Identifier
Code
Access Rights
Rights Holder
License
Rights
Accrual Method
Date Issued
Description
Language
Status
Source
Is Version Of
Replaces
Display Note
Accrual Periodicity
Date Accessioned
Date Retired
Publication State
Suppressed Record
Child Record
Mediator
Access
Created At
Updated At
Reference
B1G Image URL
ID
Centroid
GeoNames
Georeferenced
Relation
Member Of
Is Part Of
Is Replaced By
Format
File Size
Documentation
Download
FeatureServer
FGDC
Harvard Download
HTML
IIIF
ImageServer
Information
ISO19139
Manifest
MapServer
MODS
oEmbed
Index Map
TileServer
WCS
WFS
WMS

**Comment by karenmajewicz** [comment]
For reference, this is the previous order:

Title
Alternative Title
Description
Language
Creator
Creator ID
Publisher
Provider
Resource Class
Resource Type
Subject
Theme
Keyword
Temporal Coverage
Date Issued
Date Range
Spatial Coverage
Bounding Box
Geometry
GeoNames
Relation
Member Of
Is Part Of
Source
Version
Replaces
Is Replaced By
Format
File Size
WxS Identifier
Georeferenced
Documentation
Download
FeatureServer
FGDC
Harvard Download
HTML
IIIF
ImageServer
Information
ISO19139
Manifest
MapServer
MODS
oEmbed
Index Map
TileServer
WCS
WFS
WMS
Image
ID
Identifier
Code
Rights
Rights Holder
License
Access Rights
Accrual Method
Accrual Periodicity
Date Accessioned
Date Retired
Status
Publication State
Suppressed
Child Record
Mediator
Access
Created At
Updated At

**Comment by ewlarson** [comment]
This is an attribute-model issue right?

**Comment by ewlarson** [comment]
They're ordered now.

**Comment by karenmajewicz** [comment]
Verified
