### ISSUE TITLE
GEOMG Prod stalling on large bulk actions

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/geomg#276]
GEOMG Prod is running very slowly this week, and I cannot perform some bulk actions without it freezing up.

Current problem scenario:

I have about 10,000 items that have the state "Unpublished" that I want to change to "Published".  For the past few days, GEOMG has frozen up when I try to do them all at once.

1. I am able to select all the items and choose "Published" from the State dropdown.
2. After this, the site freezes. If I clear the search and start over, it occasionally throws a Rails "We're sorry, something went wrong" message.
3. I am able to publish the records in small batches, but the site loads very sluggishly.

**Comment by ewlarson** [comment]
Just seeing this issue now. Can do some debugging early this afternoon.
